- README.md
The links changed due to a change by travis. This closes #7, because travis was enabled all along, but not visible. 
I believe that the coveralls is not yet working because the travis didn't walk through once.
> Change travis-ci.org to travis-ci.com

- src/Cubes/Cubes.jl
YAXArray Construction error is now different for not enough axes and wrong sizes.
renameaxis! error gives the Axis which is not available in the cube.
This also fixes the test failure due to some BoundsError in cubes.jl
There are still some test failures due to the MockDataset, but I can't fix them myself.
> Provide errors with more info

- src/DatasetAPI/Datasets.jl
In julia 1.6 the optional parameter private in propertynames is restricted to Bool.
This change restricts it also for the method for Dataset, to avoid an ambiguity error.
This fixes the tests on julia 1.6beta.
> Restrict propertynames(Dataset, private) to avoid ambiguity error in 1.6

- .github/workflows/CI.yml
- README.md
Codecov doesn't show the files for the coverage for me. This adds coveralls so that I could see the actual files. And so that we would have both coverage reports available.
> Add Coveralls to CI.yml

- .gitignore
- benchmark/Project.toml
- benchmark/bench_mapslices.jl
- benchmark/benchmarks.jl
This PR sets up a benchmarking Skeleton, for the usage with BenchmarkCI.
We would need to merge this and then I am going to follow this up with a PR for a  setup of a benchmark GithubAction.
We can sort  the benchmarks as BenchmarkGroups from BenchmarkTools and then define the benchmarks via the  benchmarkable macro. 
You can also run these benchmarks interactively in your local REPL via:
```julia
shell> cd ~/.julia/dev/MyProject/
julia> using BenchmarkCI
julia> BenchmarkCI.judge()
...
julia> BenchmarkCI.displayjudgement()
...
```
We would need to discuss proper benchmarks for our usecases and we would also need to check, how we can also benchmark different threading and non-threading scenarios, but maybe we would need to set up another github action workflow.
> Setup benchmarks

- docs/make.jl
Hopefully this will deploy the docs. 
This fails at the moment, because the repo name is false.
> Deploy docs to meggart/YAXArrays.jl

- docs/make.jl
- docs/src/api.md
- src/Cubes/Axes.jl
- src/Cubes/Cubes.jl
- src/DAT/DAT.jl
- src/DatasetAPI/Datasets.jl
- src/YAXArrays.jl
- src/YAXTools.jl
This adds autodocs parts to the documentation.
We need to specify every submodule separately, therefore this long module list.
> Add an api reference to docs

- src/DatasetAPI/Datasets.jl
- test/Datasets/datasets.jl
This fixes #33 and another bug which led to an error when trying to save a cube that had non-standard string types (like Zarr.MaxLengthString) in it axes. I can't remember the issue right now, a hint by @noralinscheid or @felixcremer would be great
> Fix #33 and another netcdf-related bug

- src/Cubes/Axes.jl
- src/DAT/dciterators.jl
- src/DAT/tablestats.jl
This should fix #61 by showing a Progress meter of unknown length if length is unknown and #58 by throwing a warning when no common axes are found in 2 cubes
> Fix issues

- .github/workflows/benchmark.yml
This adds the benchmark workflow for github actions so that the benchmarks are run on every pull request. 
The results of the benchmarking are then added as a comment on the pull request.
> Add Benchmark workflow for GHA

- src/DAT/DAT.jl
- src/DAT/registration.jl
- src/DatasetAPI/Datasets.jl
This should drastically improve error messages in the future, so debugging mapCube functions will get easier again. In the end this was possible by defining `pmap_with_data` which allows some local intitialisation on each worker while keeping everything nicely referenced and garbage-collected after the pmap-call.
> Remove channels and go back to normal pmap

- src/Cubes/Cubes.jl
- test/Cubes/cubes.jl
This allows to call size with describtors instead of Integer values to get the size of a certain axis.
Uses findAxis in the background and therefore accepts the same descriptors. 
This is mainly interesting to call size with String or Symbol descriptors.
> Allow size with any Axis describtor

- .github/workflows/IntegrationTest.yml
This should add a github action to test ESDL.jl for every pull request
and every version tag.
This is adapted from the ChainRules project.
See here for details:
https://discourse.julialang.org/t/github-actions-workflow-for-reverse-dependency-integration-testing/53536
> Add integration test for ESDL.jl

- src/YAXArrays.jl
I have added some documentation to YAXConfig. There are two fields that I don't know what they are doing, maybe someone can add something there.
> Document YAXConfig

- src/DAT/DAT.jl
This is a first step for testing the package with Aqua and fixing ambiguities in the function definitions. 
Before I can continue with that, we would need to set up a proper testset for the axval2index and subsetting functions, because there are most of the ambiguities.
> Fix mapcube ambiguity

- src/Cubes/Axes.jl
- test/Cubes/axes.jl
This is necessary, because otherwise the subsetting with a single value fails for abstract ranges.
This is fixing the first part of issue #169 .
> Check for step length of zero in axval2index

- .github/workflows/IntegrationTest.yml
This fixes the Integration Test to actually test EarthDataLab and not the old ESDL.jl repo.
> Rename ESDL to EarthDataLab in the Integration Test

- docs/examples/HowdoI/concatenatecubes.jl
- docs/examples/HowdoI/extract_axes_names.jl
- docs/examples/HowdoI/howdoi.jl
- docs/mkdocs.yml
builds on https://github.com/JuliaDataCubes/YAXArrays.jl/pull/203
Maybe ideally one file per solution will be ok, but then adding menu links [here](https://github.com/JuliaDataCubes/YAXArrays.jl/blob/617f3a74e9f5564fa0c0f5294f77faa6168987c0/docs/mkdocs.yml#L116) is a mess, the way it is now, one just needs to add extra code at the bottom and things should just work. So, I'm doing that here.
> Fix how do i

- src/Cubes/Cubes.jl
- test/Cubes/batchextraction.jl
This closes #194 and adds a test case for it.
When we discard the axinds we also have to filter them out of the list of table columns. Otherwise we get a mismatch between table column and axis indices.
> Filter tcols in batchextract when some are not in the cube axes

- src/Cubes/Rechunker.jl
There was a performance bug when saving cubes that were much smaller than available memory where the cp[y buffer size could not be optimized. This PR adds a workaround for this case.
> Shortcut for saving small cubes

- docs/examples/UserGuide/saving.jl
- docs/make.jl
- docs/mkdocs.yml
- src/DatasetAPI/Datasets.jl
adds warning when using `overwrite=true`
> added warning

- .github/workflows/Documenter.yml
we should have a preview button for PRs, and `stable` and `latest` docs, however currently they are no where to be found 😄 , let's see is this helps. If not, then maybe we don't a Documenter key setup.
> up ci docs

- src/DatasetAPI/Datasets.jl
- test/Datasets/datasets.jl
This prints the shared axes together and indicates the additional axes per cube. This should make it easier to understand datasets with multiple axes.
This should close #192 . I still need to implement tests for this. 
The dataset printing looks now like this:
```julia
julia> ds
YAXArray Dataset
Shared Axes: 
XVals               Axis with 4 Elements from 1.0 to 4.0
YVals               Axis with 5 elements: 1 2 3 4 5 
Variables: 
avar
└── Time                Axis with 12 Elements from 2001-01-15 to 2001-12-15
└── Some Category       Axis with 3 Elements from a to c
something
└── Time                Axis with 12 Elements from 2001-01-15 to 2001-12-15
└── Some Category       Axis with 3 Elements from a to c
smaller
```
> Implement nicer printing for dataset

- .github/workflows/CI.yml
- src/DAT/DAT.jl
- test/DAT/DAT.jl
- test/DAT/mapcube.jl
The best practice that we should be following instead should come from here:
https://github.com/JuliaLang/julia/pull/48542#issuecomment-1569101718
> use static thread scheduling

- src/DatasetAPI/Datasets.jl
This would allow to enable to set backend kwargs from the savecube call. One example is compress.
> Move kwargs through the savecube machinery

- src/DatasetAPI/Datasets.jl
- test/Datasets/datasets.jl
So far cubes in a dataset that had different element types than the majority of cubes were simply submitted when calling `Cube` on a dataset. This is fixed to some extent in this PR if all types can be promoted to a discrete common type. An error message is thrown if promotion fails.
> Allow constructing cubes from different eltypes

- docs/examples/UserGuide/create_from_func.jl
I found it a bit difficult to use `mapCube` in situations, where dimensions are both removed and created. Thus, I added an example on how to create a vector data cube that aggregates points of the same region. This example is different from the others mentioned in file `create_from_func.jl`, because the transformation is not calculated elementwise as it is one in `f(lo, la, t) = (lo + la + Dates.dayofyear(t))` but requires information from the other dimensions as well, i.e. we need the longitude and latitude to calculate the aggregated value.
> Add example for vector data cube

- Project.toml
Add a last version before the breaking switch to DimensionalData, so that one could pin to version 0.4
> Increase patch number to 0.4.7

- src/Cubes/Cubes.jl
- src/DatasetAPI/Datasets.jl
This will improve the printing of the YAXArrays. 
A YAXArray is now printed using the DimensionalData show machinery with a custom `show_after` method, so that we don't print the underlying array, because that might induce a huge latency when working with external data.
The printing looks now like that:
``` julia
julia> c
384×192×251288 YAXArray{Float32,3} with dimensions: 
Dim{:lon} Sampled{Float64} 0.0:0.9375:359.0625 ForwardOrdered Regular Points,
Dim{:lat} Sampled{Float64} Float64[-89.28422753251364, -88.35700351866494, …, 88.35700351866494, 89.28422753251364] ForwardOrdered Irregular Points,
Ti Sampled{DateTime} DateTime[2015-01-01T03:00:00, …, 2101-01-01T00:00:00] ForwardOrdered Irregular Points
units: K
name: tas
Total size: 69.02 GB
```
> Fix printing of YAXArrays as DD subtype.

- Project.toml
Add compat bounds for DimensionalData, so that the auto merge in the General registry works.
> Add compat bounds for DD

- docs/examples/UserGuide/create_from_func.jl
- src/Cubes/Cubes.jl
- src/DAT/DAT.jl
This enables to use the dimensions as a cube in mapCube calls. Also reenables the documentation on filling a cube with a function.
We should be discussing in the future, whether we would like to reenable the direct use of a axis in the mapCube calls, because this was broken by the switch to DimensionalData.
> Add a YAXArray function for DD.Dimension to wrap them as a cube

- src/DAT/DAT.jl
- test/DAT/mapcube.jl
```max_cache``` in bits is fine, but not very human friendly. This is a downstream implementation of the YAXArraysToolbox package to get ```max_cache``` as e.g. ```max_cache="100MB"``` that can be useful for users of the YAXArrays package.
> max_cache human writing

- src/Cubes/Cubes.jl
> fix permutdims for dimension arguments

- src/Cubes/Cubes.jl
- test/dimarray.jl
This is similarly done for DimArray. This allows to use the NoMetadata type from DimensionalData.LookupArray in a YAXArray which is used as a default in some DimensionalData functions. 
This would close https://github.com/rafaqz/DimensionalData.jl/issues/641
I also removed a test which should rather live in DimensionalData because it does not test YAXArray functionality.
> Make Metadata a type parameter of YAXArray

- src/Cubes/Cubes.jl
- test/dimarray.jl
Reverts JuliaDataCubes/YAXArrays.jl#370
Not only breaks yax inference but also DD ones.
> Revert "Make Metadata a type parameter of YAXArray"

- src/Cubes/Cubes.jl
- test/dimarray.jl
Reverts JuliaDataCubes/YAXArrays.jl#371
My bad, different next bug. NetCDF/DiskArrays .
> Revert "Revert "Make Metadata a type parameter of YAXArray""

- .github/workflows/CI.yml
- .github/workflows/Documenter.yml
- Project.toml
- src/Cubes/Cubes.jl
- src/Cubes/Slices.jl
- src/DAT/DAT.jl
- src/DAT/dciterators.jl
- src/DAT/registration.jl
- src/DAT/tablestats.jl
- src/DatasetAPI/Datasets.jl
- src/helpers.jl
- test/Datasets/datasets.jl
This replaces the deprecated DimensionalData functions key2dim and dim2key with their new versions. 
The fix seemed to be very smooth but I am not sure whether this is breaking, because it might change the behaviour of the Ti and time axes.
> Bump DimensionalData dependency to 0.27

- src/DAT/DAT.jl
This lead to bugs when doing mapCube operations on small subsets on chunked views of arrays.
> Small fix in creation of loopchunks

- src/DatasetAPI/Datasets.jl
This tiny PR fixes how datasets show for me. This is "required" because variables in a dataset are currently printed in a single line with commas, but when a variable has extra dimensions, these dimensions are printed as new lines and mess up the overall display.
Example output with this PR:
```julia
julia> g
YAXArray Dataset
Shared Axes: 
↓ nlon Sampled{Int64} 1:1:320 ForwardOrdered Regular Points,
→ nlat Sampled{Int64} 1:1:384 ForwardOrdered Regular Points
Variables: 
lat
agessc
↓ lev Sampled{Float64} [500.0, 1500.0, …, 512502.8125, 537500.0] ForwardOrdered Irregular Points,
→ Ti  Sampled{CFTime.DateTimeNoLeap} [CFTime.DateTimeNoLeap(0001-01-15T13:00:01), …, CFTime.DateTimeNoLeap(1200-12-15T12:00:01)] ForwardOrdered Irregular Points
lon
```
versus what I think it currently looks like …
> fix show for dataset

- src/DAT/DAT.jl
- src/DatasetAPI/Datasets.jl
- test/Datasets/datasets.jl
`open_mfdataset` was broken in many cases because in the internal representation of a Datasets dimensions there was still `:time` keys mixed with `:Ti` axes. This makes the dataset consistently use `:Ti` so that axis merging works again.
> Use Ti also for dataset axis names

- Project.toml
- docs/src/UserGuide/cache.md
- src/Cubes/Cubes.jl
- src/DatasetAPI/Datasets.jl
- test/Datasets/datasets.jl
This PR makes it easy to wrap a YAXArray or Dataset into a cached dataset, which makes it much smoother for interactive plotting applications
> Expose DiskArrays.cache

- src/Cubes/Cubes.jl
- src/YAXTools.jl
- test/Cubes/transformedcubes.jl
This PR aims to fix the display order of `ConcatDiskArray`.
Unfortunately, this is going to clash with the DimensionalData.jl Generator behavior, which in a lot of cases will return a DimArray because of the DimUnitRanges returned from axes.
See also https://github.com/meggart/DiskArrays.jl/issues/185  and https://github.com/rafaqz/DimensionalData.jl/issues/771
```julia
using DimensionalData
using YAXArrays
using Zarr
using GLMakie
lon_range = X(-180:180)
lat_range = Y(-90:90)
data = [exp(cosd(lon)) + 3 * (lat / 90) for lon in lon_range, lat in lat_range]
a = YAXArray((lon_range, lat_range), data)
ds_ram = Dataset(; properties=Dict(), a)
path = tempname()
savedataset(ds_ram; path=path)
ds_disk = open_dataset(path)
a_ram = cat(ds_ram.a[X=1:100], ds_ram.a[X=101:200], dims=:X)
a_disk = …
```
> Fix collect of `ConcatDiskArray`

- docs/src/tutorials/mean_seasonal_cycle.md
This is not needed anymore since Makie can handle the time axis natively now.
I also removed the Date ticks from the last figure, because it is misleading to have Dates for 2021 when we also plot data from 2022 in the figure and it is actually the Day of year in the x-axis.
> Remove unnecessary time tick code in msc tutorial

- src/Cubes/Cubes.jl
```julia
rebuild(oldarray; data=newdata)
```
was throwing with
```julia
ERROR: UndefVarError: `dims` not defined
```
but 
```julia
rebuild(oldarray; data=newdata, dims=dims(oldarray))
```
seemed to work so I think this quick fix might help? (Not sure!)
Side question: Are there enough tests for `rebuild`?
> Fix rebuild

- src/Cubes/Cubes.jl
This error is preventing users from creating YAXArrays of Strings} and Unions that contain Strings.
closes #410
> Fix show_after error when sizeof fails to determine DataType size

- docs/src/UserGuide/read.md
> Add thread-safety note for NetCDF4

- .github/workflows/CI.yml
- README.md
- src/Cubes/Cubes.jl
- src/DatasetAPI/Datasets.jl
- test/Datasets/datasets.jl
This would fix the first part of #447 and indicates the loading status of the data of a YAXArray. 
With this PR:
```julia
julia> c
╭────────────────────────────╮
│ 2200×201 YAXArray{Int16,2} │
├────────────────────────────┴───────────────────────────────────────────────────────────────────────────── dims ┐
↓ lon Sampled{Float64} -179.99955555555556:0.00088888888888:-178.04488888890845 ForwardOrdered Regular Points,
→ lat Sampled{Float64} 79.11155555556444:-0.00088888888888:78.93377777778844 ReverseOrdered Regular Points
├────────────────────────────────────────────────────────────────────────────────────────────────────── metadata ┤
Dict{String, Any} with 8 entries:
"units"               => "Mg/ha"
"name"                => "agb"
"long_name"           => "Above-ground biomass" …
```
> Hint to data loading in show of a data cube

- src/DAT/DAT.jl
- test/DAT/mapcube.jl
This makes sure, that the errors are actually thrown and not hidden. This would fix #449 .
> Remove the on_error keyword for parallel execution

- docs/src/UserGuide/read.md
minimal docs for loading data into memory
> readcubedata, read data into memory

- src/DatasetAPI/Datasets.jl
This fixes an issue that time units are not parsed correctly when unit is specified in upper case e.g. `"Days since 1990-01-01"` instead of `"days since 1990-01-01"`.
> allow uppercase date units in cf conventions

- src/Cubes/Cubes.jl
> replace caxes by dims

- docs/src/UserGuide/read.md
- src/DatasetAPI/Datasets.jl
closes https://github.com/JuliaDataCubes/YAXArrays.jl/issues/476 https://github.com/JuliaDataCubes/YAXArrays.jl/issues/461
> new dim fix

- src/DatasetAPI/Datasets.jl
- test/Datasets/datasets.jl
This PR aims to Fix opening a `Dataset` with an `YAXArray` having a integer dimension of length 1. Thanks, @meggart, for the hint!
```julia
using YAXArrays
using Zarr
a = YAXArray(ones(5, 1))
ds = Dataset(layer=a)
path = tempname() * ".zarr"
savedataset(ds; path=path)
ds2 = open_dataset(path)
```
results in error:
```
ERROR: BoundsError: attempt to access 0-element Vector{Int64} at index [1]
Stacktrace:
[1] throw_boundserror(A::Vector{Int64}, I::Tuple{Int64})
@ Base ./essentials.jl:14
[2] getindex
@ ./essentials.jl:916 [inlined]
[3] testrange(x::Vector{Int64})
@ YAXArrays.Datasets ~/.julia/packages/YAXArrays/x5iTf/src/DatasetAPI/Datasets.jl:321
[4] toaxis(dimname::String, g::ZarrExt.ZarrDataset, offs::Int64, len::Int64)
@ YAXArrays.Datasets …
```
> Fix open dataset with length 1 dim
