JuliaDataCubes/YAXArrays.jl

src/DatasetAPI/Datasets.jl
test/Datasets/datasets.jl

Subset more than one YAXArray in a Dataset if all YAXArrays share the same Axis.

Subsetcube for Dataset

---

src/DAT/DAT.jl
test/DAT/mapcube.jl

Special case sinlge-value outputs

---

src/YAXTools.jl
test/runtests.jl
test/tools.jl

Fixes #133 and adds unit tests to detect breakage in the future

Fix loadorgenerate

---

src/Cubes/Axes.jl

no code changes. Only fine styling and fine reordering for better readability for new users
finished:
- added documentation headers
- moved all using/import statements to top
- reordering of functions and introduction of comment-headers
open:
- better documentation
- all import/using necessary?
- `convert_time` necessary?
open question:
- `import ..Cubes: caxes, Cubes` Is Cubes a sibling or more like a parent?

codestyling in axes.jl

---

src/Cubes/Cubes.jl

Changed some small portions in codestyling for better readability for new users of YAXArrays.
Todo:
* move Axes submodule into full sibling module
* Discussion: Should subsetting/slicing an own file or even an own submodule?

Codestyle cubes.jl

---

src/Cubes/Axes.jl
test/Cubes/axes.jl
test/Cubes/transformedcubes.jl

implemented the AbstractArrayInterface. This changes the concatention of Arrays which lets a test fail

added AbstractArrayInterface for the CubeAxis

---

src/Cubes/Axes.jl

Fix subset when RangeAxis contains vector

---

src/Cubes/Axes.jl
src/Cubes/Rechunker.jl
src/Cubes/TransformedCubes.jl

PR to fix all bugs appearing in #163

Fix edltests

---

src/DAT/DAT.jl

I started to write doc strings also for the internal functions in DAT.jl to also better understand what is happening myself. I am going to slowly add more docstrings to all of the small functions.

Add doc strings for functions and types in DAT.jl

---

docs/examples/HowdoI/extract_axes_names.jl
docs/examples/UserGuide/openZarr.jl
docs/mkdocs.yml

1. trying to fix again reading a Zarr file from the cloud 
2. Adding a new section: How do I ...

adds How do I section

---

src/Cubes/TransformedCubes.jl

Should fix https://github.com/JuliaDataCubes/EarthDataLab.jl/issues/284

Fix Concatbug

---

src/DAT/DAT.jl

Fix bug when permuting loop axes dimension

---

src/DatasetAPI/Datasets.jl

This is a start to better document the exported functions of the DatasetAPI

Write some docstrings for exported functions in DatasetAPI

---

.gitignore
docs/examples/UserGuide/create_from_func.jl
docs/examples/contribute/contribute.jl
docs/mkdocs.yml
docs/src/stylesheets/custom.css

- add example on how to create a data cube given a function that acts on space and time
- some tweaks to docs
- adds guide for contributors to docs

add c from f & up docs contribute

---

src/DAT/DAT.jl
src/DAT/registration.jl
test/Datasets/datasets.jl

Attempt to fix  #227. Error no longer occurs.

Fixed the type issue

---

src/DAT/dciterators.jl

WIP: Fix bug when broadcasted axes in table are in front position

---

docs/examples/HowdoI/howdoi.jl
docs/examples/UserGuide/applyfunctions.jl
docs/examples/UserGuide/examples_from_esdl.jl
docs/mkdocs.yml

MSC example for a single pixel included to 'Apply functions on YAXArrays'
The ESDL example section is created 
and some edits on How do I

adding: MSC example, esdl example section , +edits

---

docs/examples/UserGuide/applyfunctions.jl

@linamaes please see changes and open an issue if is not the output you intended.

a fix using Makie

---

src/Cubes/Rechunker.jl

This should fix the problems during rechunking in https://github.com/JuliaSoilModels/HybridComission/pull/111

Try several optimisers and give up otherwise

---

src/Cubes/Rechunker.jl
src/DAT/DAT.jl
src/DAT/dciterators.jl
src/DAT/tablestats.jl
src/DatasetAPI/Datasets.jl
test/dimarray.jl

This shoudl not be necessary, but it looks that in some situations for long-running jobs memory usage keeps increasing until running into an OOM error. We already had a use case where manually calling gc helped, it would be good if others could test as well if this would help for their use case @TabeaW @Qfl3x .

Manually run gc after chunk processing

---

docs/examples/HowdoI/howdoi.jl

Examples of `mapslices` and `CubeTable` for the How do I section

examples for how do i

---

docs/Project.toml
docs/src/.vitepress/theme/index.ts
docs/src/tutorials/mean_seasonal_cycle.md

no orama, but fixes and up .toml

---

Project.toml

This PR is to check whether docs building works. @lazarusA

Bump version to 0.5.8

---

src/Cubes/Cubes.jl

Address typo that has been bugging me for some time.

Fix typo: lenghts -> lengths

---

docs/src/.vitepress/config.mts

this PR effectively add the cache docs to the documentation page.

fix cache docs

---

docs/src/UserGuide/faq.md
docs/src/UserGuide/write.md

this should close https://github.com/JuliaDataCubes/YAXArrays.jl/issues/413 and https://github.com/JuliaDataCubes/YAXArrays.jl/issues/76

issues 413 and 76

---

Project.toml
src/DatasetAPI/Datasets.jl
test/Datasets/datasets.jl

Fix open_mfdataset

---

src/DatasetAPI/Datasets.jl
test/Datasets/datasets.jl

TODO: Update docstring (and maybe documentation)

Add option to skip keys when opening datasets

---

Project.toml

bump breaking

---

docs/src/components/AsideTrustees.vue

Fix https://github.com/JuliaDataCubes/YAXArrays.jl/issues/522#issuecomment-3199454725

update Package Ecosystem links
